CREATE TABLE counter (
    id VARCHAR(255) PRIMARY KEY,
    delta BIGINT
);
ALTER TABLE counter ALTER COLUMN delta SET NOT NULL;

CREATE TABLE gauge (
    id VARCHAR(255) PRIMARY KEY,
    value DOUBLE PRECISION
);
ALTER TABLE gauge ALTER COLUMN value SET NOT NULL;
